### ISSUE TITLE
Are differences in WGBS and RRBS associated with coverage

### ISSUE THREAD

**Issue by mgavery** [hputnam/Meth_Compare#10]
How do we pull coverage info out of methylkit (like writing % methylation file?)
Can we make coverage "bedGraphs" to visualize this in IGV

**Comment by mgavery** [comment]
I think the visualization in IGV would help because we could see if these sites were at the end of the fragments or some kind of weird bias in this subset of sites that differ between the methods

**Comment by sr320** [comment]
I think it would we worth pulling in bams from url to see this.

**Comment by sr320** [comment]
They are already sorted and  indexed - so should not be too much of a pull.

**Comment by kubu4** [comment]
Reminder to check IGV settings to make sure you're not just viewing mean values by default!

**Comment by sr320** [comment]
Yep we zoomed in to confirm

**Comment by hputnam** [comment]
This was an issue with trimming. We used TrimGalore! with RRBS option for RRBS and the others were treated as WGBS.
