### ISSUE TITLE
Confirm satisfaction with TrimGalore output

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#14]

**Comment by hputnam** [comment]
Can you link to these files when they are available? Are we confirming by 1) fastqc, 2) IGV specifically checking ends, and 3) higher correlations in corr plots?

**Comment by sr320** [comment]
At this point fastqc - essentially wanting a green light from the group that I can proceed with bismark on file set.

**Comment by mgavery** [comment]
next steps:
1) look at FastQC on trimmed reads comparing fastp v. TrimGalore 
2) "MethExtract" the aligned TrimGalore data to run methylKit to compare the TrimGalore'd sample 13 RRBS v. WGBS (@sr320 - did you run this already? can you provide a link to the .cov files?)

**Comment by shellywanamaker** [comment]
@mgavery here's @sr320 's [alignments](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/030520-fr01/Mcap_TG/) generated by his [job24.sh](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/030520-fr01/job24.sh) of the [RRBS TrimGalore data](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200306/) from [20200306](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200306_TrimGfroger.sh), which doesn't contain Sample6 because I canceled the job to free up the node. 

So no .cov files have been generated yet for TrimGalore data

**Comment by sr320** [comment]
@mgavery I am happy to run jobs to look at @shellytrigg 's TG data, but was currently waiting to run https://github.com/hputnam/Meth_Compare/blob/master/scripts/mox/0313_1100.sh
on all TG data at once when it was available. 

Note to all the script is a full compilation from take TG data to the "end" on mox so have a look.

**Comment by shellywanamaker** [comment]
@sr320 could you confirm which bismark reports we compared between the [preliminary RRBS TG](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200306/) alignments and the preliminary RRBS fastp alignments? I think we only looked at this for sample 13 because that was the only TG alignment that finished at the time. If I am recalling correctly, I think the TG alignments showed ~6% mCpG and the fastp alignments showed ~12% mCpG?

**Comment by mgavery** [comment]
@sr320 I think it would be great to look at one of the RRBS TG samples that you were aligning on Monday (I think sample 13) in methylKit to see if those artifacts go away.  If you ran meth_extract on it, I would use the .cov file

**Comment by sr320** [comment]
Yes I believe we did look at only 13 just after alignment...
Here is the TG report https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/030520-fr01/Mcap_TG/Meth13_R1_001_val_1_bismark_bt2_PE_report.txt

**I think we might have overlooked "Mapping efficiency"** ⚠️ 
**And the fact we were looking at the wrong genome!**  

Here is the report on 13 fastp. 
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/030520-fr01/Mcap_full-u100M/Meth13.fastp-trim.202003062040_R1_001_bismark_bt2_PE_report.txt


Because TG was on Pact we could look at other samples...

**Comment by sr320** [comment]
>@sr320 I think it would be great to look at one of the RRBS TG samples that you were aligning on Monday (I think sample 13) in methylKit to see if those artifacts go away. If you ran meth_extract on it, I would use the .cov file

@mgavery I think we could look at sample 4 (Pact) - based on the output I seemed to have run The TG samples against Pact. Would that be helpful?

**Comment by shellywanamaker** [comment]
I am currently running [methylation extractor](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200313/RRBS_TG_MethExt.sh) on  @sr320 's [alignments](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/030520-fr01/Mcap_TG/). 

.cov.gz files will be [here](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200313/)

**Comment by sr320** [comment]
> I am currently running methylation extractor on @sr320 's alignments.

> .cov.gz files will be here

Do note these will not be merged correctly. Might be best we chat via zoom on current intent?

**Comment by shellywanamaker** [comment]
sure

**Comment by shellywanamaker** [comment]
TrimGalore output mox path:
/gscratch/scrubbed/strigg/analyses/20200311/WGBS_MBD
/gscratch/scrubbed/strigg/analyses/20200311/RRBS

**Comment by shellywanamaker** [comment]
**MultiQC output for TG data:**

- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/RRBS/FASTQC/multiqc_report_1.html](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/RRBS/FASTQC/multiqc_report_1.html)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/WGBS_MBD/FASTQC/multiqc_report.html](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/WGBS_MBD/FASTQC/multiqc_report.html)

**MultiQC output for FastP data (includes before and after trimming with FastP):**

- [https://gannet.fish.washington.edu/Atumefaciens/20200305_methcompare_fastp_trimming/multiqc_report.html](https://gannet.fish.washington.edu/Atumefaciens/20200305_methcompare_fastp_trimming/multiqc_report.html)

**Comment by sr320** [comment]
I now have this running to test TG - getting @mgavery some merged.cov files
https://github.com/hputnam/Meth_Compare/blob/master/scripts/mox/0313_1340.sh

**Comment by mgavery** [comment]
@shellytrigg, could you tell me what the val1 and val2 are in the TG folder?

**Comment by shellywanamaker** [comment]
@mgavery "val1" and "val2" are part of the trimmed read filenames (e.g. Meth6_R1_001_val_1.fq.gz and Meth6_R2_001_val_2.fq.gz). They are generated by TrimGalore after the program validates the trimmed reads. See [slurm-2098069.out](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/slurm-2098069.out). In the slurm.out file which shows the screen output from the script, you will see a section that says
```
Validate paired-end files Meth10_R1_001_trimmed.fq.gz and Meth10_R2_001_trimmed.fq.gz
file_1: Meth10_R1_001_trimmed.fq.gz, file_2: Meth10_R2_001_trimmed.fq.gz

>>>>> Now validing the length of the 2 paired-end infiles: Meth10_R1_001_trimmed.fq.gz and Meth10_R2_001_trimmed.fq.gz <<<<<
Writing validated paired-end read 1 reads to Meth10_R1_001_val_1.fq.gz
Writing validated paired-end read 2 reads to Meth10_R2_001_val_2.fq.gz
```
I see in the [RRBS directory](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/RRBS/) that there are also some files from before the validation (e.g. Meth5_R1_001_trimmed.fq.gz). These normally are deleted by the program, but because I started copying files over before the script actually finished running it looks like a couple were copied over before the program deleted them. I will remove the two files ending with "_trimmed.fq.gz" because those are pre-validation. For alignment and downstream analysis, we only want to use the files that have "val" in their names.

**Comment by shellywanamaker** [comment]
@mgavery the script has now finished and I am still currently copying the complete data over to Gannet.

**Comment by shellywanamaker** [comment]
@mgavery @sr320 all TG files and reports are completely copied over to Gannet here: [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/). 

You can find links to MultiQC reports 4 comments above, so we can do the fastp vs. TG comparison.

**Comment by sr320** [comment]
Here are 10M read subset merged cov files for assessment / confirmation of TG. 

![wb](http://gannet.fish.washington.edu/seashell/snaps/IMG_2833.HEIC_2020-03-14_07-04-19.png)



https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth10_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth11_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth12_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/nodedup/Meth13_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/nodedup/Meth14_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/nodedup/Meth15_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth16_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth17_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth18_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

as code
```
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth10_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth11_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth12_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/nodedup/Meth13_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/nodedup/Meth14_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/nodedup/Meth15_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth16_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth17_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031320-TG-bs/Mcap_tg/dedup/Meth18_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
```

**Comment by mgavery** [comment]
![Meth_Compare_MethCompare_correlation_MC_WvR_TG_jpg_at_master_·_hputnam_Meth_Compare](https://user-images.githubusercontent.com/4512578/76684629-c8824080-65ca-11ea-8dfb-59e725553b7e.png)

**Comment by mgavery** [comment]
I think we're good to go based on correlation plots.  Haven't looked at IGV

**Comment by sr320** [comment]
I can get an IGV instance up so we can spot check some read ends.

**Comment by mgavery** [comment]
I also did a differential methylation analysis with MBD v RRBS.  There were 567 overlapping regions and 18 CpG that were >50% different in methylation.  Those sites are in close proximity on chr 268 and 2374 

here's the chr 268 example
> myDiff_MvR_TG_50p
methylDiff object with 18 rows
--------------

```
   chr  start    end strand       pvalue       qvalue meth.diff
21 268 541820 541822      * 3.147450e-14 6.039982e-14 -72.15100
22 268 541823 541825      * 8.378336e-15 1.700568e-14 -73.18165
23 268 541829 541831      * 5.749688e-16 1.348563e-15 -74.63925
24 268 541836 541838      * 1.499844e-12 2.380476e-12 -65.82260
25 268 541858 541860      * 6.963410e-10 8.646544e-10 -58.33634
26 268 541871 541873      * 9.296348e-11 1.234198e-10 -63.60209
```

**Comment by mgavery** [comment]
That would be a good place to look for IGV

**Comment by sr320** [comment]
Ones listed seem to be good ..

![igv](http://gannet.fish.washington.edu/seashell/snaps/IGV_2020-03-15_05-59-23.png)

igv session: `https://raw.githubusercontent.com/hputnam/Meth_Compare/master/genome-feature-files/0315_0600-igv_session.xml`

video: https://washington.zoom.us/rec/share/_NZ6N4rt60JOR5Xv7WL_ZrIGI77haaa81CgX-vMNxBlxHhag6wMgIkX1ZXqxnlXV

**Comment by mgavery** [comment]
Now MBD is the odd man out. Ha! Calling higher methylation at a few sites more than the other methods.  Because these differences are restricted to a few scaffolds, I don't think it's a systemic trimming or other type of bioinformatic issue.  Will be interesting to look into these more though.

Otherwise, I think the RRBS looks like it's trimmed well and that 100% methylation artifact at the end has been removed with the TrimGalore.  My vote is to proceed to mapping.
