### ISSUE TITLE
update stats table(s) with new trimming results

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#15]
here is the link to the table: [https://docs.google.com/spreadsheets/d/1MVQmSq6ff-aeLUNhMDsGDDHdRb8D530XZ-AnvRQ3PwY/edit#gid=0](https://docs.google.com/spreadsheets/d/1MVQmSq6ff-aeLUNhMDsGDDHdRb8D530XZ-AnvRQ3PwY/edit#gid=0).

This will be a supplementary table to complement table 1

**Comment by hputnam** [comment]
https://docs.google.com/spreadsheets/d/1MVQmSq6ff-aeLUNhMDsGDDHdRb8D530XZ-AnvRQ3PwY/edit#gid=0
