### ISSUE TITLE
CG tracks - create track and evaulate CG coverage for each method

### ISSUE THREAD

**Issue by mgavery** [hputnam/Meth_Compare#16]
1. Create a CG track (bed file)
2. Determine how many ("density") of CG in the covered region for each method

**Comment by sr320** [comment]
CG gffs
C1 - https://d.pr/f/aq6v1T 
Mcap - https://d.pr/f/sFWAa1
Pact - https://d.pr/f/g4qeyt

**Comment by sr320** [comment]
Will take these into bedtools and compare to sample files. including unioned bedgraphs

**Comment by hputnam** [comment]
@sr320 do these files live on gannet somewhere? I am looking to wget them to the server and the dropler doesn't generate links

**Comment by sr320** [comment]
Syncing up to https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/genome-feature-files/ now

**Comment by hputnam** [comment]
Do they only appear when they are fully synced? Should I wait for an indicator to start downloading?

**Comment by sr320** [comment]
Best practices would have you download, md5 and confirm below to make sure exact same file.

```
MD5 (C1_CpG.gff) = 926ee736a6a27554ad91b1106e6b1256
MD5 (Mcap_CpG.gff) = b58ce71fea86dd966d0b6b521262ca11
MD5 (Pact_CpG.gff) = 3cd51218f6b1951a4aed2945458d93e4
```

I predict it will be 30 minutes before all files are there.

**Comment by sr320** [comment]
nb 13-16 @ https://github.com/hputnam/Meth_Compare/tree/master/scripts
Concerned about a few numbers

**Comment by sr320** [comment]
Still needs attention... waiting to confirm analysis up this point is validated.
