### ISSUE TITLE
update stats table with multiqc data from .bams from full alignment

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#18]
here is the link to the table: https://docs.google.com/spreadsheets/d/1MVQmSq6ff-aeLUNhMDsGDDHdRb8D530XZ-AnvRQ3PwY/edit#gid=0.

This will be a supplementary table to complement table 1

**Comment by sr320** [comment]
@hputnam is this what you did yesterday?

**Comment by hputnam** [comment]
Yes, partially... I am still working on alignment numbers
![Screen Shot 2020-03-24 at 11 10 04 AM](https://user-images.githubusercontent.com/5198996/77442500-d56c1480-6dc0-11ea-8cf2-38563bb6b383.png)

**Comment by hputnam** [comment]
completed table online.. need to make this into a formatted table
https://docs.google.com/spreadsheets/d/1MVQmSq6ff-aeLUNhMDsGDDHdRb8D530XZ-AnvRQ3PwY/edit#gid=0
