### ISSUE TITLE
Map reads and extract methylation for Pact reads against C1 Symbiodinium genome

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#20]
Can we run the same mapping for Pact with the C1 Symbiodinium Genome as well?

**Comment by sr320** [comment]
Running now - code https://github.com/hputnam/Meth_Compare/blob/master/scripts/mox/0323_1000.sh

**Comment by sr320** [comment]
update status: aligned 7/9 files

**Comment by sr320** [comment]
little bug in code (fixed) running with mod script https://github.com/hputnam/Meth_Compare/blob/master/scripts/mox/0323_1000-2.sh
Running now. will end up at https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032320-Pact-C1/Pact_C1/

**Comment by sr320** [comment]
Complete! https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032320-Pact-C1/Pact_C1/
