### ISSUE TITLE
Mapping to lambda for conversion efficiency

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#21]
@sr320 did you already complete the mapping to the lambda spike for conversion efficiency?

**Comment by sr320** [comment]
Only at a `-u` subset level. Should I run full data set at it?

**Comment by sr320** [comment]
Running full set now - code: https://github.com/hputnam/Meth_Compare/blob/master/scripts/mox/0325_0800.sh

**Comment by sr320** [comment]
Job complete results @ https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032520-lambda/lambda_tg/

Certainly worth a good look. Does not seem good.
