### ISSUE TITLE
generate a conical coverage track for each coral methylome using 9 samples at 5x coverage

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#28]

**Comment by sr320** [comment]
Mcap available @ https://github.com/hputnam/Meth_Compare/blob/master/scripts/10-Mcap-Canonical-Coverage-Track.ipynb

**Comment by sr320** [comment]
Pact available @ https://github.com/hputnam/Meth_Compare/blob/master/scripts/11-Pact-Canonical-Coverage-Track.ipynb

**Comment by sr320** [comment]
really cool comparisons can be made with output as I have methylation level for each sample written out.

Direct link to bedgraphs 
https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/analyses/10-unionbedg/

**Comment by hputnam** [comment]
@sr320 is it possible to do this for C1 as well?

**Comment by sr320** [comment]
Running Pact on C1 now... any hints at where Mcap libraries mapped to C1 live?

**Comment by hputnam** [comment]
There is no mapping for Sym for Mcap. We do not have genomes for their dominant symbionts (C17/C31, D1)

**Comment by sr320** [comment]
Pact (1-9) on C1 @ https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/analyses/10-unionbedg/

nb https://github.com/hputnam/Meth_Compare/blob/master/scripts/12-Pact-C1-Canonical-Coverage-Track.ipynb

**Comment by hputnam** [comment]
@sr320 I think the C1 got mapped or copied as P acuta instead. The file size is the same and the scaffold name matches the Pacuta genome and not the C1 genome

**Comment by hputnam** [comment]
something has gone wrong by step 7 in your notebook... scaffolds should look like this 
![Screen Shot 2020-04-01 at 4 57 55 PM](https://user-images.githubusercontent.com/5198996/78185988-f7593d00-7439-11ea-9776-59e6fcaf78fa.png)

**Comment by sr320** [comment]
I believe it is now resolved… please do confirm

**Comment by hputnam** [comment]
Yes, the C1 scaffolds are there. Thanks!

**Comment by sr320** [comment]
Revisiting unionbed... nothing is dependent on this, rather a curiosity to see how much data we have per species..

**Comment by sr320** [comment]
@shellytrigg  you have completed this?

**Comment by sr320** [comment]
Yes
see https://github.com/hputnam/Meth_Compare/issues/43#issuecomment-619280654
