### ISSUE TITLE
Describe gene mapping differences across methods

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#3]

**Comment by sr320** [comment]
look at reports

**Comment by mgavery** [comment]
Questions:
1. Are the fragment (insert) sizes the same for all libraries? How does bismark (bowtie) get the information about insert size, can't this affect mapping?

2. Is read quality different - this should be obvious from reports

3. Run fastqc on the trimmed reports, this should help compare

**Comment by kubu4** [comment]
>Are the fragment (insert) sizes the same for all libraries? How does bismark (bowtie) get the information about insert size, can't this affect mapping?

> Is read quality different - this should be obvious from reports

> Run fastqc on the trimmed reports, this should help compare


Already done:

MultiQC report for RRBS/WGBS:

https://gannet.fish.washington.edu/Atumefaciens/20200305_methcompare_fastp_trimming/multiqc_report.html

**Comment by mgavery** [comment]
Why is MBD-BS-Seq not mapping as well?
-one possibility is that symbiont DNA is highly methylated and is getting preferentially pulled down relative to host DNA for this method.  
-test this by mapping to some type of in silico symbiont genome

**Comment by mgavery** [comment]
symbiodinium genome and methylation references: https://www.nature.com/articles/s42003-018-0098-3
![Symbiodinium_genomes_reveal_adaptive_evolution_of_functions_related_to_coral-dinoflagellate_symbiosis___Communications_Biology](https://user-images.githubusercontent.com/4512578/76151152-9a4eaf00-6066-11ea-9bf9-9edf0cd1838c.png)

**Comment by kubu4** [comment]
Consider sorting reads taxonomically before mapping?

**Comment by mgavery** [comment]
How do you do that?

**Comment by kubu4** [comment]
I've done this using MEGAN6 to separate dinoflagellates from crab sequences.

**Comment by kubu4** [comment]
Basically, do some BLASTing and InterProScan stuff and then the software assigns taxonomies to individual reads, then allows you to pull reads at any level of taxonomic hierarchy.

**Comment by hputnam** [comment]
We were able to use Sym C1 for tests of alignments in the Pacuta data.
