### ISSUE TITLE
Confirm definition and calculation of conversion efficiency

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#30]
From Zymo RRBS kit manual 
"To calculate the bisulfite conversion rate, we suggest using the percentage of the unmethylated cytosines in non-CpG contexts for mammalian samples; if the samples may be significantly methylated on cytosines in non-CpG contexts, the provided unmethylated E.coli (Escherichia coli) genomic DNA (D5016)1 can be spiked into the input samples (0.5-5 wt%, i.e., 0.5-5 ng of the unmethylated E.coli genomic DNA to 100 ng of input genomic DNA) before starting the library preparation, and calculate the percentage of the unmethylated cytosines in non-CpG contexts on the aligned E.coli reads. The reference genome of E.coli strain K-12 substrain MG16552 can be used for alignment and analysis."

We used the included unmethylated E.coli (Escherichia coli) genomic DNA (D5016)

**Comment by hputnam** [comment]
"the percentage of the   unmethylated cytosines in non-CpG contexts on the aligned E.coli reads"

"% methylation   (context) = 100 * methylated Cs (context) / (methylated Cs (context) +   unmethylated Cs (context))."

Conversion Efficiency = (sum of unmeth C's in CHG, CHH, and Unk / sum of meth and unmeth C's in CHG, CHH, and Unk)*100


https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032820-lambda/lambda_tg/
--

**Comment by shellywanamaker** [comment]
@hputnam do  Cs in the "Unknown context" need to be included here?
