### ISSUE TITLE
List one thing important to showcase in manuscript

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#31]
Add at least one thing to [the manuscript below the white board picture](https://docs.google.com/document/d/1pSTNOp6GkpNPGdNryksoPSolYYG4OxWZ7QTt88MQSIY/edit#bookmark=id.kxjqchuop1qm) that you think is important to showcase. 

There are already a few ideas there, but we can add more and/or start elaborating on the idea (e.g. what formatted data is needed for the analysis, how it could be visualized, etc.)

**Comment by yaaminiv** [comment]
done

**Comment by shellywanamaker** [comment]
done
