### ISSUE TITLE
create CCGG (MspI cut site) tracks

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#32]
@sr320 can you create CCGG tracks for Pact and Mcap to confirm RRBS data line up near MspI cut sites (and that WGBS and MBD data do not)?

**Comment by sr320** [comment]
Available @ https://osf.io/x5waz/files/

**Comment by shellywanamaker** [comment]
@sr320 how did you make this track? Is the code in the repo?

**Comment by sr320** [comment]
Galaxy - fuzznuc, no

**Comment by shellywanamaker** [comment]
gotcha, thanks!
