### ISSUE TITLE
md5 check script

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#35]
I think it would be good to have a mox script that will check all md5s on "transfers"

**Comment by kubu4** [comment]
If using rsync for transfers, there's a built-in checking that automatically occurs. However, if you want a stricter level of verification, rsync has a checksum option available, too.

**Comment by sr320** [comment]
Gotcha - but this is for after-the-fact.

**Comment by kubu4** [comment]
I don't think I follow...

**Comment by kubu4** [comment]
Sorry, I didn't make it clear in my initial response. Rsync can verify transfers after they've been completed, by generating/comparing checksums after a file is transferred.

**Comment by sr320** [comment]
We need to go back and check files that have been previously transferred without rsync. 
Specifically for validating this multi-person pipeline contains accurate output without error.
https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md

 For context, errors are suspected. 

Way more than you want to know :) https://washington.zoom.us/rec/share/tdwyBpzS8j1IT5XduBqBe69-EKbUeaa80Ske__JZn0gJ1cIQwWIbPrndJ4DcOqvr

**Comment by shellywanamaker** [comment]
I ran this on mox (with script [20200410_MD5compareALL.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200410_MD5compareALL.sh)):

```
find /gscratch/scrubbed/sr320/031520-TG-bs \
-type f -exec md5sum {} + \
>  all_031520-TG-bs_files_MOX_md5sum.txt
```

and am currently running this on Ostrich:

```
find /Volumes/web/seashell/bu-mox/scrubbed/031520-TG-bs \
-type f -exec md5sum {} + \
> all_031520-TG-bs_files_GANNET_md5sum.txt
```

I'm going to compare hashes between the two files using the code below:

```
#compare files with awk: if an MD5 hash matches between files, the hash from each input file will be printed; if a hash does not match, only the hash from the second input file will be printed. 

awk 'NR==FNR{a[$1]=$1;next}{if($1 in a)print a[$1],$1;else print $1}' \
all_031520-TG-bs_files_MOX_md5sum.txt  \
all_031520-TG-bs_files_GANNET_md5sum.txt \
> awk_matchALLbmrk_results.txt

# count lines in MD5 results

wc -l awk_matchALLbmrk_results.txt \
all_031520-TG-bs_files_MOX_md5sum.txt \
all_031520-TG-bs_files_GANNET_md5sum.txt
```

All input and output files can be found on Gannet here: [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200410/](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200410/)

**Comment by shellywanamaker** [comment]
Ran this on Ostrich with Gannet mounted:

```
#compare files with awk: if an MD5 hash matches between files, the hash from each input file will be printed; if a hash does not match, only the hash and corresponding file name from the second input file will be printed. 

awk 'NR==FNR{a[$1]=$1;next}{if($1 in a)print a[$1],$1;else print $1, "no_match", $2}' \
all_031520-TG-bs_files_MOX_md5sum.txt  \
all_031520-TG-bs_files_GANNET_md5sum.txt \
> awk_matchALLbmrk_results.txt

cat awk_matchALLbmrk_results.txt | \
awk '{if($2=="no_match")print $0}' 

cat awk_matchALLbmrk_results.txt | \
awk '{if($2!~/no_match/)print $0}'

cat awk_matchALLbmrk_results.txt | \
awk '{if($2!~/no_match/)print $0}' |\
wc -l 

wc -l all_031520-TG-bs_files_MOX_md5sum.txt 

```

output here: [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200410/bmrk_md5_check_output.txt](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200410/bmrk_md5_check_output.txt)

All file hashes match between Mox '/gscratch/scrubbed/sr320/031520-TG-bs' and Gannet [https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/), integrity good. @mgavery @yaaminiv @hputnam  .cov files (and other bismark output) can be found here:

- [Mcap_WGBS_MBD](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/Mcap_tg/dedup/)
- [Mcap_RRBS](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/Mcap_tg/nodedup/)
- [Pact_WGBS_MBD](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/Pact_tg/dedup/)
- [Pact_RRBS](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/Pact_tg/nodedup/)

**Comment by shellywanamaker** [comment]
currently running the same MD5 checks on C1 alignments on Mox and Gannet

**Comment by shellywanamaker** [comment]
**CONFIRMED** C1 alignment files on Mox '/gscratch/scrubbed/sr320/032320-Pact-C1/Pact_C1' match those on Gannet [https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032320-Pact-C1/Pact_C1/](https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032320-Pact-C1/Pact_C1/). 

MD5 check analysis here:  [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/)

- mox script to generate MD5 hashes: [20200415_MD5check_C1.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200415_MD5check_C1.sh)
- mox script slurm file: [slurm-2494974.out](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/slurm-2494974.out)
- Mox MD5 file hashes: [all_032320-Pact-C1_files_MOX_md5sum.txt](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/all_032320-Pact-C1_files_MOX_md5sum.txt)
- script run on ostrich to check MD5s: [20200415_MD5check_mox_v_gannet_Pact_C1.sh)](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/20200415_MD5check_mox_v_gannet_Pact_C1.sh)
- ostrich script log file: [screenlog.0](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/screenlog.0)
- Gannet MD5 file hashes: [all_032320-Pact-C1_files_GANNET_md5sum.txt](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/all_032320-Pact-C1_files_GANNET_md5sum.txt)
- awk output confirming hashes match: [awk_matchALLbmrk_results.txt](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200415/awk_matchALLbmrk_results.txt)
