### ISSUE TITLE
5x vs. 10x data?

### ISSUE THREAD

**Issue by yaaminiv** [hputnam/Meth_Compare#42]
Are we using 5x or 10x data for everything? I know the union files used for the circos plots was 5x, and I used 10x data for the CpG characterization. Just want to make sure I'm staying consistent with whatever we decided!

**Comment by mgavery** [comment]
Good question - I was using 5x for correlation plots, but would feel more comfortable with 10x for this comparison. @hputnam, preferences? I just tried uniting all Mcap samples using a 5x and 10x cutoff and it didn't change the number of overlapping loci at all (1851 loci @ 5x and 1851 loci @ 10)

**Comment by yaaminiv** [comment]
Use 5x for this week, revisit 10x later
