### ISSUE TITLE
Union bedgraphs for circos plots?

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#43]
@sr320 a few questions on the union bedgraphs: 

1) how were the union bedgraphs used in the Circos plots generated and should the code be added to the [Meth_Compare_Pipeline.md](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md)?

2) do we need to run an MD5 check on these files? If so, can you post locations of the files that need MD5 check?

**Comment by sr320** [comment]
Would have to ask @hputnam re Circos. 
Quite possible she created her own union files.

**Comment by shellywanamaker** [comment]
@sr320 got it. I was remembering @hputnam mentioning something about a jupyter notebook that created these files but I'm not sure if I'm remembering correctly.

**Comment by sr320** [comment]
I created files in notebooks 10 and 11 @ https://github.com/hputnam/Meth_Compare/tree/master/scripts

**Comment by hputnam** [comment]
I used the output of these at 5x https://github.com/hputnam/Meth_Compare/issues/28

**Comment by yaaminiv** [comment]
Last week we discussed looking over the union files, so I'm doing that now...

I'm not familiar enough with `unionbedg` to see if there's anything fishy going on there, but from what I can tell it seems to work fine.

I went through each step of the calculations in [this script](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Circos_Meth_Plot.R) to generate averages for WGBS/RRBS/MBD-BS and looked at the range of the methylation values. I didn't see anything out of the ordinary. @hputnam did you mention that there were some methylation values over 100%, or am I imagining that?

**Comment by sr320** [comment]
I indicated that…

see https://github.com/hputnam/Meth_Compare/blob/master/scripts/15-Pact-CpG-coverage.ipynb

have data for 15758676 CpGs, but only 9155620 CpGs in genome.

**Comment by shellywanamaker** [comment]
I tested sorting the bedgraphs before running unionBed and it seemed to solve the problem of CpG sites being listed more than once in the output:

[10-Mcap-Canonical-Coverage-Track-STRIGG.ipynb
](https://github.com/hputnam/Meth_Compare/blob/master/scripts/10-Mcap-Canonical-Coverage-Track-STRIGG.ipynb
)

[11-Pact-Canonical-Coverage-Track-STRIGG.ipynb](https://github.com/hputnam/Meth_Compare/blob/master/scripts/11-Pact-Canonical-Coverage-Track-STRIGG.ipynb)

**Comment by shellywanamaker** [comment]
@hputnam here are the union bedgraphs output from sorting the input before running unionBedGraph:

[https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/Mcap_union_5x.bedgraph](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/Mcap_union_5x.bedgraph)

[https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/Pact_union_5x.bedgraph](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/Pact_union_5x.bedgraph)

Pact_union_5x.bedgraph has 7326298 unique CpG lines.

Mcap_union_5x.bedgraph has 13340269 unique CpGs line.

Is that what you got in your R attempt at merging?

**Comment by shellywanamaker** [comment]
@yaaminiv are the 5x union bed files you are using in your script https://github.com/hputnam/Meth_Compare/blob/master/scripts/Characterizing-CpG-Methylation-5x-Union.ipynb from https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/analyses/10-unionbedg/ or from https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg ?

The 5x union bed files @sr320 generated that live here https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/analyses/10-unionbedg/ contain duplicates because they were not sorted prior to performing the command unionBed. Particularly https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/analyses/10-unionbedg/Pact_union_5x.bedgraph contains 15758676 CpG loci, but there are only 9155620 CpGs in genome (as @sr320 indicated above). 

I found that after sorting bedgraphs and then running unionBed:

-  Pact_union_5x.bedgraph should have 7326298 unique CpG loci (https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/Pact_union_5x.bedgraph)

- Mcap_union_5x.bedgraph has 13340269 unique CpG loci (https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/Mcap_union_5x.bedgraph)

**Comment by yaaminiv** [comment]
@shellytrigg ah no I didn't use the revised version of the union bedfiles. I'll fix that now.

**Comment by yaaminiv** [comment]
Reran script with revised union bedfiles and updated figures. No major changes. Will update results.
