### ISSUE TITLE
Align Pact reads against Pact/C1 Pangenome

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#45]

**Comment by sr320** [comment]
Align with 100k subsetting https://github.com/hputnam/Meth_Compare/blob/master/scripts/mox/0417_1100.sh

and the Merged coverage files where C1 has been removed are at
https://github.com/hputnam/Meth_Compare/tree/master/analyses/pan-genome-cov
named `*Pact-viaPan*`

**Comment by sr320** [comment]
ICYMI @mgavery

**Comment by mgavery** [comment]
No overlaps for all 3 methods.

38 overlaps at 5x for MBD v. RRBS.  https://github.com/hputnam/Meth_Compare/blob/master/analyses/MethCompare_correlation_Pact_pan_TG_041420.jpg

I don't think we can conclude much here.  There's a lot of variation even with RRBS with this low number of sites.  

Can you run a larger subset?

**Comment by sr320** [comment]
Started the full set at the same time and imagine it will be done by Friday…

I can also to a 500k subset in the meantime if you think it would be useful.

**Comment by mgavery** [comment]
500k would still be <100 loci to compare.  Maybe 1 million? then could have ~400 loci for MBD v. RRBS.  I still don't think we would get much with WGBS even with that subset

**Comment by sr320** [comment]
Running 1M now.. though pretty sure this is close to full run...

**Comment by sr320** [comment]
1M subset data @ https://github.com/hputnam/Meth_Compare/tree/master/analyses/pan-genome-cov-1M

**Comment by mgavery** [comment]
With the 1M subset, I think it's easier to see that the issue still exists even when you allow reads to map to C1.  I just did MBD v. RRBS - there were 362 overlapping loci and 77 were >50% diff in meth (always higher in MBD). That's about 20% of loci which is similar to what we were seeing in the table with the full data set.  Corr plot: https://github.com/hputnam/Meth_Compare/blob/master/analyses/MethCompare_correlation_Pact_pan_TG_042120.jpg

**Comment by sr320** [comment]
Full set @ 
https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/analyses/pan-genome-cov-full/

**Comment by mgavery** [comment]
Full set doesn't change the picture from the 1 Million subset.  MBD still the outlier.  Example corr plot MBD v RRBS full dataset: https://github.com/hputnam/Meth_Compare/blob/master/analyses/CorrPlots_Pact_PanGenome_fulldata/MethCompare_correlation_Pact_panRvM_TG_043020.jpg

Also added stats to the common loci sheet.  Still about 20% of common loci are called >50% higher meth in MBD
