### ISSUE TITLE
Revert repo to commit  e9cf685?

### ISSUE THREAD

**Issue by kubu4** [hputnam/Meth_Compare#52]
While attempting to fix significant issues with a local version of this repo (https://github.com/RobertsLab/resources/issues/917), the resolution for that issue seems to have created an insane number of conflicts for everyone else.

In my opinion, the easiest, least painful way to resolve this would be to revert to the last commit before I screwed things up trying to fix the issue linked above.

After that, it would mean that @mgavery would have to re-run anything that she had previously run on Emu (the computer which had problems with the local version of the repo) since the commit referenced in this post title.

What does everyone think about this?

**Comment by mgavery** [comment]
That's not a problem for me.

**Comment by yaaminiv** [comment]
Not a problem for me either

**Comment by sr320** [comment]
Sounds good

**Comment by kubu4** [comment]
OK, I'll get the repo reverted on Emu and then push to GitHub. I'll post here when I've done that and then I'll please need someone to try to pull to make sure there are no conflicts.

**Comment by kubu4** [comment]
Alrighty, would someone mind trying to pull the repo to their computer and let me know what happens? Thanks @sr320 @yaaminiv @mgavery! Sorry for the craziness!

**Comment by kubu4** [comment]
Ok, actually I was able to pull to Emu without issue! I think this is good...

**Comment by kubu4** [comment]
To clarify (since you might be thinking "Duh, of course you could pull to Emu - this is where all the junk/changes was happening). I actually forked this repo to my account, cloned it to my computer, reset to the desired commit, initiated a pull request for this Meth_Compare repo, and accepted the pull request. Then, since none of that was done on Emu, I ran `git pull` on Emu and it pulled perfectly. Fingers crossed....

**Comment by yaaminiv** [comment]
@kubu4 Still getting conflicts on genefish (7 files total, 21 conflicts):

<img width="298" alt="Screen Shot 2020-04-26 at 1 29 50 PM" src="https://user-images.githubusercontent.com/22335838/80318879-037ab500-87c2-11ea-8c20-a9e4ba4c6216.png">

*edited 4/26/2020 at 1:35 p.m. to add the number of files with merge conflicts*

**Comment by yaaminiv** [comment]
Should I commit all files that do not have conflicts?

**Comment by kubu4** [comment]
Hmmm, interesting. I'd say resolve the conflicts first. How many conflicts are there? Also, not sure to resolve conflicts in PDF files...

**Comment by yaaminiv** [comment]
In the GUI it looks like I can "choose" a version of the PDF file I want to maintain. I assume I'd use the file from origin/master (what I'm "pulling" from)?


<img width="469" alt="Screen Shot 2020-04-26 at 1 38 01 PM" src="https://user-images.githubusercontent.com/22335838/80319054-28235c80-87c3-11ea-929b-364d1f2bae86.png">

**Comment by kubu4** [comment]
I have no idea. I guess I'd keep whichever is newer...

**Comment by yaaminiv** [comment]
> I guess I'd keep whichever is newer...

How can I tell which version is newer?

**Comment by kubu4** [comment]
My only suggestion is to look at that file on GitHub repo and see when it was last modified (committed) and look at the timestamp of that same file in your local copy of the repo.

**Comment by yaaminiv** [comment]
Well I have no idea what just happened but the files with conflicts now do not have any conflicts so I was able to pull the repo successfully!

<img width="300" alt="Screen Shot 2020-04-26 at 1 49 51 PM" src="https://user-images.githubusercontent.com/22335838/80319402-cf54c380-87c4-11ea-891e-f1bc252f0e38.png">

**Comment by yaaminiv** [comment]
I think the files that magically no longer have merge conflicts were files that @hputnam @sr320 and @shellytrigg were working on. Can y'all confirm that the version of these files that are in the repo are "correct"?

**Comment by kubu4** [comment]
Um, okay! Hopefully that's good?!?! 

Admittedly, I was a bit surprised that you encountered any conflicts. The steps I took basically are a "cheat", in that I've "rewound" the entire repository to an earlier point in time. So, when anyone pulls, it should rewind the local repo. And with that, no conflicts (unless someone has active changes/commits that have note been pushed since @hputnam last commit on Friday).

**Comment by shellywanamaker** [comment]
@kubu4 @yaaminiv @sr320 I am reviewing files that I worked on recently and I'm noticing they now contain some weird formatting (e.g "<<<<<<< HEAD", "=======", and ">>>>>>>dab158436a754cc3fd162c4bb321b7185cad521a";see [C1_alignments_descriptive_stats.csv](https://github.com/hputnam/Meth_Compare/blob/master/Output/C1_alignments_descriptive_stats.csv), [Pact_Mcap_alignments_descriptive_stats.csv](https://github.com/hputnam/Meth_Compare/blob/master/Output/Pact_Mcap_alignments_descriptive_stats.csv) for an example), which does not exist in my local repository (I have not pulled since Friday). I think this happened here in @yaaminiv commit: https://github.com/hputnam/Meth_Compare/commit/731206446b01934af7c031005c7ac56afd918e04


Is the best thing to do right now to do the following?:

1. move my recent work from my local Meth_Compare repository 
2. pull the current Meth_Compare
3. add my recent work back into Meth_Compare
4. push

**Comment by kubu4** [comment]
Those are conflict indicators marking the regions of the file that have a conflict. Usually you have to resolve them before they can get pushed/pulled...

To answer your questions:

1. yes.

2. Delete local repo and then clone.

3. Yes.

4. Yes.

**Comment by shellywanamaker** [comment]
done
