### ISSUE TITLE
Create bed files of MBD v WGBS and RRBS DMC for genome feature annotation

### ISSUE THREAD

**Issue by mgavery** [hputnam/Meth_Compare#63]
@yaaminiv , passing you these bed files for the 50% DMC between
MBDvWGBS: https://github.com/hputnam/Meth_Compare/blob/master/analyses/Pact_methDiff/Pact_WvM_50pMethDiff.bed
MBDvRRBS:https://github.com/hputnam/Meth_Compare/blob/master/analyses/Pact_methDiff/Pact_RvM_50pMethDiff.bed

for annotation of genome feature from your pipeline.

**Comment by mgavery** [comment]
Just throwing this out there that the 50% cutoff is pretty random.  See histograms of diff meth for WGBS v MBD for example: https://github.com/hputnam/Meth_Compare/blob/master/analyses/Pact_methDiff/MethCompare_DiffMethHisto_Pact_WvM_TG_050420.jpg

**Comment by yaaminiv** [comment]
Not sure how you wanted them visualized, but for now I generated count summary tables in [this script](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Identifying-Genome-Features-Summary-Plots.Rmd) from data I generated in [this pipeline](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Identifying-Genomic-Locations.ipynb):

- [overlap counts](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Pact/Pact-DMC-Feature-Overlap-counts.txt)
- [overlap percents](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Pact/Pact-DMC-Feature-Overlap-percents.txt)

**Comment by yaaminiv** [comment]
Will do statistical comparison for all vs. method-associated DMC information

**Comment by yaaminiv** [comment]
DMC chi-sq test output here: https://github.com/hputnam/Meth_Compare/blob/be25687cdb0d1e47472680cd3da27430b5a589cd/analyses/Identifying-genomic-locations/Pact/Pact-DMC-Genomic-Location-StatResults.txt

**Comment by hputnam** [comment]
changing statistical approach for this.
