### ISSUE TITLE
New union bedgraphs with read count data

### ISSUE THREAD

**Issue by yaaminiv** [hputnam/Meth_Compare#64]
The current union bedgraphs only have percent methylation data. I characterized CpG distributions by simply averaging the percent methylation across the three samples, which is not correct. To calculate % meth of a CpG in the union data set, I need to do the following:

(count methylated sample 1 + count methylated sample 2 + count methylated sample 3)/(total reads sample 1 + total reads sample 2 + total reads sample 3)

I need new union bedgraphs with the count of methylated reads and total reads for each sample. Does this file exist?

**Comment by shellywanamaker** [comment]
@yaaminiv this does not currently exist to my knowledge. I believe we only have union bedgraphs that are % methylation and that are total CpG counts. If I can make union bedgraphs for mCpG counts and then they could be merged with the corresponding total CpG counts union bedgraphs. Would that work?

**Comment by yaaminiv** [comment]
@shellytrigg I would need two columns per sample:

- # reads methylated for a single CpG (row)
- total reads for a single CpG (row)

If you could make a file like that, that would be great! The individual sample bedgraphs that we have only have the calculated % meth for each CpG (row), so I don't know where the other information lives.

**Comment by hputnam** [comment]
do we have this in the tab file i will be using for the DMG analysis?

**Comment by yaaminiv** [comment]
Decided this was no longer needed since percent meth averages are not the same as averaging 3 percents (percent meth is variable of interest)
