### ISSUE TITLE
Functional Annotation of Mcap and Pact gene sets

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#69]
blast to swissprot and use uniprot to obtain GO and KO

**Comment by shellywanamaker** [comment]
KO is listed under phylogenomic databases
![Screen Shot 2020-05-22 at 10 11 28 AM](https://user-images.githubusercontent.com/4720221/82692472-a46b5d00-9c14-11ea-9308-2ae76d34906e.png)

**Comment by hputnam** [comment]
Montipora
predicted protein - http://cyanophora.rutgers.edu/montipora/Mcap.protein.fa.gz
nucleotide CDS - http://cyanophora.rutgers.edu/montipora/Mcap.mRNA.fa.gz

**Comment by sr320** [comment]
Here is a product for Mcap https://github.com/sr320/nb-2020/blob/master/M_capitata/analyses/Mcap-GO-KO-Kegg.tab

**Comment by sr320** [comment]
Pact protein fasta?

**Comment by hputnam** [comment]
Working plan to get the Pact protein fasta...
Use the Structural_annotation_abintio.gff to pull T1 only (longest transcript called by AUGUSTUS) and pull the coding sequence from that gff and the protein seq seq from that gff for all predicted genes.  This seems most comparable to the gene CDS and protein files available for Mcap, which was also called with AUGUSTUS.  @sr320 @shellytrigg @yaaminiv @mgavery @kubu4 any objections?

**Comment by sr320** [comment]
I guess I am surprised there is a genome and no gene / protein fasta already.

**Comment by shellywanamaker** [comment]
@sr320 genome and shell script for getting protein fasta are linked in issue #71

**Comment by sr320** [comment]
I have been double coding all morning :) I given in, @hputnam can I just have the fasta?

**Comment by hputnam** [comment]
Link to Pacuta Augustus predicted protein fasta https://osf.io/shqjx/

MD5 has been checked from local computer to OSF

**Comment by sr320** [comment]
now have a blast annotation https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/061620-Pact-annotation/Pact_blastp_sp.tab
Moving on to GO Kegg etc..

**Comment by sr320** [comment]
Here is the product for Pact:
https://github.com/sr320/nb-2020/blob/master/P_acuta/analyses/Pact-GO-KO-Kegg.tab

**Comment by hputnam** [comment]
@sr320 can you please add the uniprot download or version date?

**Comment by sr320** [comment]
download date 2019-0109
