### ISSUE TITLE
Update scripts + README

### ISSUE THREAD

**Issue by yaaminiv** [hputnam/Meth_Compare#70]
- Clean up code in scripts
- Explain what analysis each script is used for in [README](https://github.com/hputnam/Meth_Compare/blob/master/scripts/README.md)

**Comment by yaaminiv** [comment]
Started putting my scripts in the order they should be run: https://github.com/hputnam/Meth_Compare/blob/master/scripts/README.md

**Comment by shellywanamaker** [comment]
- all R scripts should go in [scripts](https://github.com/hputnam/Meth_Compare/tree/master/scripts) directory
- all R scripts should be able to be run from [Meth_compare.Rproj](https://github.com/hputnam/Meth_Compare/blob/master/Meth_Compare.Rproj)
     - remove other Rproj files in [analyses](https://github.com/hputnam/Meth_Compare/tree/master/analyses) directory
     - change any paths dependent on repo docs to be compatible with running the R script from [Meth_compare.Rproj](https://github.com/hputnam/Meth_Compare/blob/master/Meth_Compare.Rproj)

**Comment by hputnam** [comment]
It looks like all scripts have gone into the analyses directory instead.

**Comment by shellywanamaker** [comment]
all scripts should be in [code directory](https://github.com/hputnam/Meth_Compare/tree/master/code) now and issue has moved here: https://github.com/hputnam/Meth_Compare/issues/95
