### ISSUE TITLE
Need all gene CpG intersection information to link to expression and GO

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#73]

**Comment by yaaminiv** [comment]
The intersection files are large in the `.gitignore` but you can generate them in this script: https://github.com/hputnam/Meth_Compare/blob/master/scripts/Characterizing-CpG-Methylation-5x.ipynb

**Comment by sr320** [comment]
another option would be adding to https://osf.io/x5waz/

**Comment by hputnam** [comment]
@yaaminiv that would be great if you are able to do that. Then we don't need to double code it.

**Comment by yaaminiv** [comment]
@hputnam Oh! Forgot they're also on `gannet`, but I can add to OSF if needed:

Mcap: https://gannet.fish.washington.edu/spartina/Meth_Compare/analyses/Characterizing-CpG-Methylation-5x/Mcap/ 

Ex. filename: https://gannet.fish.washington.edu/spartina/Meth_Compare/analyses/Characterizing-CpG-Methylation-5x/Mcap/Meth12_R1_001_val_1_bismark_bt2_pe._5x.bedgraph.bed-mcGenes

Pact: https://gannet.fish.washington.edu/spartina/Meth_Compare/analyses/Characterizing-CpG-Methylation-5x/Pact/

Ex. filename: https://gannet.fish.washington.edu/spartina/Meth_Compare/analyses/Characterizing-CpG-Methylation-5x/Pact/Meth3_R1_001_val_1_bismark_bt2_pe._5x.bedgraph.bed-paGenes

**Comment by sr320** [comment]
By all means, let’s not have anyone double code :)
