### ISSUE TITLE
Choose color palette and 3 specific colors for methods and standardize across graphics

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#74]
@yaaminiv @shellytrigg any ideas?

**Comment by hputnam** [comment]
It looks like for most figures, WGBS is green, RRBS is blue, and MBDBS is red. Figure 1 has WGBS and RRBS reversed.

**Comment by yaaminiv** [comment]
I think on Slack we decided to move away from red/green contrasts and go with orange, green, and purple instead! I can put together a color palette and confirm accessibility with `dichromat`.

**Comment by yaaminiv** [comment]
WGBS: green
RRBS: purple
MBD-BS: orange

I have 2 different color palettes: one with 3 shades and one with 5 shades. I have the code for each palette, hex codes for each color, and the revised plot so you can see what the colors look like.

## 3 shades (CpG methylation status)

```
plotColors <- c(rev(RColorBrewer::brewer.pal(3, "Greens")), 
                rev(RColorBrewer::brewer.pal(3, "Purples")), 
                rev(RColorBrewer::brewer.pal(3, "Oranges"))) #Create vector of WGBS, RRBS, and MBD colors
```

Hex codes:

Greens:
-"#31A354"
- "#A1D99B"
- "#E5F5E0"

Purples:
- "#756BB1"
- "#BCBDDC"
- "#EFEDF5"

Oranges:
- "#E6550D"
- "#FDAE6B"
- "#FEE6CE"

![Screen Shot 2020-06-17 at 3 57 14 PM](https://user-images.githubusercontent.com/22335838/84958922-37cc6c80-b0b3-11ea-9ab4-3f153e59a1bc.png)
## 5 shades (CpG genomic location)

```{r}
plotColors2 <- c("grey20", "grey40", "grey60", "grey80", "grey100", 
                rev(RColorBrewer::brewer.pal(5, "Greens")), 
                rev(RColorBrewer::brewer.pal(5, "Purples")), 
                rev(RColorBrewer::brewer.pal(5, "Oranges")))
```

Hex codes (not including greyscale): 

Greens: 
- "#006D2C" 
- "#31A354" 
- "#74C476" 
- "#BAE4B3" 
- "#EDF8E9" 

Purples:
- "#54278F"
- "#756BB1"
-"#9E9AC8"
-"#CBC9E2"
-"#F2F0F7"

Oranges:
- "#A63603" 
- "#E6550D"
- "#FD8D3C"
- "#FDBE85"
- "#FEEDDE"

![Screen Shot 2020-06-17 at 3 56 48 PM](https://user-images.githubusercontent.com/22335838/84958891-27b48d00-b0b3-11ea-9c92-5e3a4606478e.png)
