### ISSUE TITLE
Check gene.gff has 63227 genes

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#75]
there are genes with names starting with g and with adig, need to check we pulled them all

**Comment by yaaminiv** [comment]
Will include GeMoMa genes/CDS/introns etc. in Mcap tracks

**Comment by yaaminiv** [comment]
Remade genome feature tracks. Gene track now has 63227 genes

gene: https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap.GFFannotation.gene.gff
CDS: https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap.GFFannotation.CDS.gff
intron: https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap.GFFannotation.intron.gff
upstream flanks: https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap.GFFannotation.flanks.Upstream.gff
downstream flanks: https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap.GFFannotation.flanks.Downstream.gff
intergenic: https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap.GFFannotation.intergenic.bed

Also remade Mcap figure based on overlaps with additional GeMoMa/adig genes. MBD is no longer the best.

![Screen Shot 2020-06-22 at 9 52 49 AM](https://user-images.githubusercontent.com/22335838/85314289-234ef200-b46e-11ea-958d-671e84644514.png)

**Comment by hputnam** [comment]
wrote a script to fix the Mcap gff file to correct formatting of GeMoMa genes
https://github.com/hputnam/Meth_Compare/blob/master/scripts/Fix_GeMoMa.R
