### ISSUE TITLE
Confirm # of common 5x CpG loci 

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#87]
I made this script (https://github.com/hputnam/Meth_Compare/blob/master/analyses/Coverage_analysis/PCA_5xUnionBedCpGs.Rmd) to create PCA plots for common 5x CpG loci from 5x union bedgraphs (generated by [10-Mcap-Canonical-Coverage-Track-STRIGG.ipynb](https://github.com/hputnam/Meth_Compare/blob/master/scripts/10-Mcap-Canonical-Coverage-Track-STRIGG.ipynb) and [11-Pact-Canonical-Coverage-Track-STRIGG.ipynb](https://github.com/hputnam/Meth_Compare/blob/master/scripts/11-Pact-Canonical-Coverage-Track-STRIGG.ipynb) and located here: https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/10-unionbedg/)

The number of loci I found covered by all samples at 5x coverage was:

- 4666 for Mcap ([Mcap_union5xCpG_PCAinput.tsv](https://github.com/hputnam/Meth_Compare/blob/master/Output/Mcap_union5xCpG_PCAinput.tsv))
- 93714 for Pact ([Pact_union5xCpG_PCAinput.tsv](https://github.com/hputnam/Meth_Compare/blob/master/Output/Pact_union5xCpG_PCAinput.tsv))

This is different than the number of common loci that @mgavery found in her [corr plot analysis](https://github.com/hputnam/Meth_Compare/blob/master/analyses/CorrPlots_CommonDataset/MethCompare_CorrPlot_methylKit_analysis.R). She found:

- 1861 for Mcap
- 33591 for Pact

@mgavery can you confirm that you are filtering for 5x coverage? I found that the MethylKit methRead command by default uses a 10x cutoff in the user manual (https://www.bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html) unless the mincov parameter is specified. Could this be the reason for the discrepancy?

**Comment by mgavery** [comment]
Removing the filter step and just uniting the samples based on the 5x 'mincov' in methRead

-4666 for Mcap
-93714 for Pact

Whew!  Thanks SO much Shelly for looking into this!!
