### ISSUE TITLE
Recharacterize locations for DMC

### ISSUE THREAD

**Issue by yaaminiv** [hputnam/Meth_Compare#90]
Get DMC BEDfile from @mgavery and rerun script with revised genome feature tracks

**Comment by mgavery** [comment]
This is most relevant for Pact_WvM and Pact RvM, but all pairwise comparisons are provided: https://github.com/hputnam/Meth_Compare/tree/master/analyses/CorrPlots_CommonDataset/Pact_Mcap_DMC_bedfiles

**Comment by yaaminiv** [comment]
Ran all of them just in case we wanted the information!

*M. capitata*:

- [DMC location counts](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Mcap/Mcap-DMC-Feature-Overlap-counts.txt)
- [DMC location percents](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Mcap/Mcap-DMC-Feature-Overlap-percents.txt)

*P. acuta*:

- [DMC location counts](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Pact/Pact-DMC-Feature-Overlap-counts.txt)
- [DMC location percents](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Pact/Pact-DMC-Feature-Overlap-percents.txt)
