### ISSUE TITLE
Identify location of Lambda conversion and remove xls file when code is posted

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#92]
https://github.com/hputnam/Meth_Compare/blob/master/metadata/lambda_conversion.xlsx

**Comment by shellywanamaker** [comment]
This code is here: https://github.com/hputnam/Meth_Compare/blob/master/code/CompareConversionEfficiency.Rmd

Conversion efficiencies calculated by code are in this table here: https://github.com/hputnam/Meth_Compare/blob/master/OLD_Output/lamda_vs_estimated_conversion_efficiency.csv

**Comment by hputnam** [comment]
Do we know where the code is for the mapping and extraction?

**Comment by shellywanamaker** [comment]
it is here: https://github.com/hputnam/Meth_Compare/blob/master/code/mox/0328_0400.sh
