### ISSUE TITLE
Finalize NCBI submission of raw sequence data

### ISSUE THREAD

**Issue by hputnam** [hputnam/Meth_Compare#97]

**Comment by hputnam** [comment]
@kubu4 Would it be possible for you to do this if we provide all the metadata?

**Comment by kubu4** [comment]
Definitely. Has the data been uploaded to NCBI already? If yes, I'll need access to the submission. If not, I'll need access to the sequencing data to upload to NCBI.

**Comment by shellywanamaker** [comment]
@hputnam can you confirm the following:

1. Did you start a BioProject for this already?
2. The raw data in this directory (e.g. Meth1_R1_001.fastq.gz) are the correct files? 
3. This is the correct meta data:  https://github.com/hputnam/Meth_Compare/blob/master/metadata/30-244831635_sample_submission_form.csv
